name: Bonjour
on:
  - push
jobs:
  dire_bonjour:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19
      - name: Echo npm version
        run : npm -v
      - name: Install NPM dependencies
        run: npm install
      - name: Run npm Lint
        run: npm run lint