name: Bonjour
on:
  - push
jobs:
  dire_bonjour:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Build Image Docker
      run: docker image build --tag=docker-node:1.0.0 ./.github/workflows/
    - name: Run npm lint in container
      run: docker run --rm docker-node:1.0.0 npm run lint