name: Bonjour
on:
  - push
  - pull_request
jobs:
  dire_bonjour:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Build Image Docker
      run: docker image build --tag=docker-node:1.0.0 -f ./.github/workflows/Dockerfile ./
    - name: Run npm lint in container
      run: docker run --rm docker-node:1.0.0 npm run lint
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        username: schaudhryy
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: Push if on `main`
      uses: docker/build-push-action@v4
      if: startsWith(github.ref, 'refs/tags/')
      with:
        push: true
        context: ./
        file: ./.github/workflows/Dockerfile
        tags: schaudhryy/sayhello:${{ github.ref_name }}
