name: Bonjour
on:
  - push
jobs:
  dire_bonjour:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          node-version: 18
      - name: Install NPM dependencies
        run: npm install
      - name: Run npm Lint
        run: npm run lint